### ISSUE TITLE
Black inventory

### ISSUE THREAD

**Issue by Adiyot** [Shadows-of-Fire/EnderBags#1]
13.2. Ender bag's inventory are not gray, but black; very hard to see anything. This bug was in previous versions too.
https://imagizer.imageshack.com/img921/660/9lQzqJ.png

**Comment by Shadows-of-Fire** [comment]
Thats, uh, super weird.  I have no idea what could be causing that.
What other mods are you using?  I don't see this happen with just EB installed.

**Comment by Adiyot** [comment]
Same thing even if EB's alone. All other inventory's interfaces working good.

**Comment by Shadows-of-Fire** [comment]
Forge version?

**Comment by Adiyot** [comment]
The mod was run on 25.0.44, 25.0.54, 25.0.73.

**Comment by Shadows-of-Fire** [comment]
If this issue still happens on 3.0.2, please reopen this.  I think I've fixed it, but it's hard to test as it never happened for me in the first place.
