### ISSUE TITLE
[1.14.3] Crash on world creation. java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by ProsperCraft** [Shadows-of-Fire/EnderBags#4]
If you plan to update to 1.14.3 here is the crash that happens on world creation.

https://gist.github.com/ProsperCraft/a00de806056b6e82ff2b747e6b680851

**Comment by ProsperCraft** [comment]
Closed with a patch?

**Comment by Shadows-of-Fire** [comment]
This was never a bug, just the result of running a 1.14.2 mod on 1.14.3

**Comment by litjohn50** [comment]
1.14.2 is as gone as 1.8

If you could port to 1.14.3 that would be nice
