### ISSUE TITLE
Items disappearing when taking bag out of hotbar

### ISSUE THREAD

**Issue by ZadexSniper** [Shadows-of-Fire/EnderBags#6]
best explained via lil vid https://youtu.be/UiIgsmGxbZI. Seems to only happen when in creative or going from survival to creative

**Comment by Shadows-of-Fire** [comment]
what mod/forge/mc version?

**Comment by ZadexSniper** [comment]
Sorry it took this long for me to reply, EnderBags-1.14.4-4.2.0 with forge-1.14.4-28.0.76

**Comment by Shadows-of-Fire** [comment]
I think this has to do with how the creative inventory manages items.  Not sure if I can resolve this at all, as it appears to be a vanilla thing.  Will look into it some more.

**Comment by Shadows-of-Fire** [comment]
This is caused by the following vanilla/forge issue: https://github.com/MinecraftForge/MinecraftForge/issues/4580
Can't fix it from my end.
