### ISSUE TITLE
deleted items when changing from creative in survival

### ISSUE THREAD

**Issue by captcookie** [Shadows-of-Fire/EnderBags#7]
Forge Version 31.1.46 1.15.2

It happens every time you have items in bag and switch from survival to creative and creative to survival. Poof! Everything gets deleted.

**Comment by captcookie** [comment]
It might be bc of mine and slash... I reported to them too.

**Comment by Shadows-of-Fire** [comment]
It's just because of how the share tag feature works, just gonna disable it since it seems to cause more harm than good
