### ISSUE TITLE
Payload Issue?

### ISSUE THREAD

**Issue by Athaias** [Shadows-of-Fire/EnderBags#9]
I put all of my things in an enderbag and now when I log on and try to open the bag I crash and get an error telling me payload my not be larger then 32767 bites... so I can't grab the bag or open it to get my stuff out now without crashing.

**Comment by Shadows-of-Fire** [comment]
Unfortunately I can't prevent you from nbt-bombing yourself.  You'll have to nbt edit your playerdata to fix the problem.

**Comment by Athaias** [comment]
I'm sorry I have never had this issue before can you tell me how to do that and will that delete all of my items?

**Comment by Shadows-of-Fire** [comment]
You'll need a tool like this https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac to edit your player data file.  As for losing all your items, well, that depends how you do the editing.

**Comment by Athaias** [comment]
okay. thank you. do you know if the issue is just me and if I would be able to prevent this from happening again and maybe give the bag to my friend and have them take out my items or if they would also crash? Sorry for all of the questions.

**Comment by Shadows-of-Fire** [comment]
This issue occurs when you add too much NBT data to any item.  You just need to refrain from adding a ton of nbt-items to a backpack.  Typically other items that also hold items.

**Comment by Athaias** [comment]
okay so like putting shulkers and backpacks filled with items into other backpacks such as the enderbags.

**Comment by Athaias** [comment]
so I fixed the issue some how.... I had a backpack on and put the full ender bags in the backpack and I was crashing any time I tried to take them out and open them. 

I put the backpack on the wall (Thankfully this mod lets me) and put a hopper under it to get the ender bags into a mc chest. Now I can take them out and open them?
